version: 0.2
env:
    variables:
        SPRING_PROFILES_ACTIVE: "dev"
phases:
    install:
        runtime-versions:
            java: corretto21
    build:
        commands:
            - echo Build started on `date`
            - sam build
    post_build:
         commands:
            - cd .aws-sam/build/GalleryFunction
            - zip -r app.zip *
            - aws lambda update-function-code --function-name NDABackend-FractalFunction8D81D62B-vr3ZXsbLsvAg --zip-file fileb://app.zip
            - echo Build completed on `date`
