version = 0.1
[default.deploy.parameters]
stack_name = "nickdenningart-gallery"
resolve_s3 = true
s3_prefix = "nickdenningart-gallery"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
